config/routes.rb
Rails.application.routes.draw do
  resources :positions

root :controller => 'welcome', :action => :index

end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:symbol, :price, :number)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

 def index


  response = HTTParty.get("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.xchange%20where%20pair%20in%20(%22USDILS%22)&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=")
  @usdils = response["query"]["results"]["rate"]["Rate"].to_f

  response = HTTParty.get("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.xchange%20where%20pair%20in%20(%22EURILS%22)&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=")
  @eurils = response["query"]["results"]["rate"]["Rate"].to_f

  l = Position.all

  @dic = {}

  l.each do |p|

    response = HTTParty.get("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%3D%22#{p.symbol}%22&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=")
    currentPrice = response["query"]["results"]["quote"]["LastTradePriceOnly"].to_f
    @dic[p] = currentPrice

  end

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matistocks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navigation' %>
<%= yield %>

</body>
</html>

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Positions</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Price</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.symbol %></td>
        <td><%= position.price %></td>
        <td><%= position.number %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @position.symbol %>
</p>

<p>
  <strong>Price:</strong>
  <%= @position.price %>
</p>

<p>
  <strong>Number:</strong>
  <%= @position.number %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <a class="navbar-brand" href="/">Mati Bot's Stocks</a>
  </div>
</nav>

app/views/welcome/index.html.erb
<table class="table">
  <% totalBought = 0 %>
  <% totalNow = 0 %>
  <tr>
    <td><b></b></td>
    <td><b></b></td>
    <td><b>USDILS</b></td>
    <td><b><%= @usdils %></b></td>
    <td><b>EURILS</b></td>
    <td><b><%= @eurils %></b></td>
    <td><b></b></td>
    <td><b></b></td>
  </tr>
  <tr>
    <td><b>symbol</b></td>
    <td><b>price</b></td>
    <td><b>number</b></td>
    <td><b>current</b></td>
    <td><b>bought</b></td>
    <td><b>current</b></td>
    <td><b>current-ILS</b></td>
    <td><b>change</b></td>
  </tr>
  <% @dic.each do |k,v| %>
    <tr>
      <td><%= k.symbol %></td>
      <td><%= k.price %>$</td>
      <td><%= k.number %></td>
      <td><%= v %></td>
      <td><%= (k.number * k.price).round(2) %>$</td>
      <td><%= (k.number * v ).round(2) %>$</td>
      <td><%= (k.number * v * @usdils).round(2) %>₪</td>
      <td><%= (100*(v/k.price - 1)).round(2) %>%</td>
      <% totalBought += (k.number * k.price).round(2) %>
      <% totalNow += (k.number * v ).round(2) %>
    </tr>
  <% end %>
  <td><b></b></td>
  <td><b></b></td>
  <td><b></b></td>
  <td><b></b></td>
  <td><b><%= totalBought.round(2) %>$</b></td>
  <td><b><%= totalNow.round(2) %>$</b></td>
  <td><b><%= (totalNow * @usdils).round(2) %>₪</b></td>
  <td><b><%= (100*(totalNow/totalBought - 1)).round(2) %>%</b></td>
</table>